{% set name = "napari-stracking" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 25c3e262e2b769655f76fabe352737d9ee09fad596fcf23f2e6a2b3903bd6cdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - stracking >=0.1.9

test:
  imports:
    - napari_stracking
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/sylvainprigent/napari-stracking
  summary: Linking and tracks analysis
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
